name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER_USERNAME
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Print all environment variables
        run: printenv

      # Step 3: Log in to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

      # Step 4: Build the Docker image m
      - name: Build Docker image
        run: |
          docker build -t suriyashanmugam/job-portal-ui:latest .
          docker tag suriyashanmugam/job-portal-ui:latest suriyashanmugam/job-portal-ui:${GITHUB_SHA}

      # Step 5: 
      - name: Push Docker image
        run: |
          docker push suriyashanmugam/job-portal-ui:latest
          docker push suriyashanmugam/job-portal-ui:${GITHUB_SHA}
